env.run(['cp', 'more', 'dmesg', 'kill', 'agetty', 'sulogin', 'nologin', 'ctrlaltdel', 'fsfreeze',
         'blkdiscard', 'blkzone', 'chcpu', 'pivot_root', 'switch_root', 'hwclock', 'fsck.minix',
         'mkfs.minix', 'mkfs', 'mkfs.bfs', 'raw', 'fsck.cramfs', 'mkfs.cramfs', 'blockdev', 'chrt',
         'ionice', 'taskset', 'col', 'colcrt', 'colrm', 'hexdump', 'rev', 'ul', 'script', 'scriptreplay',
         'scriptlive', 'setterm', 'mesg', 'wall', 'last', 'utmpdump', 'chmem', 'flock', 'choom', 'ipcmk',
         'ipcrm', 'ipcs', 'renice', 'setsid', 'setarch', 'fallocate', 'nsenter', 'cal', 'logger', 'look',
         'mcookie', 'namei', 'whereis', 'uuidgen', 'rename', 'getopt', 'hardlink', 'isosize', 'readprofile',
         'ldattach', 'rtcwake', 'uuidd', 'fdformat', 'addpart', 'delpart', 'resizepart', 'configure', 'libtool',
         'mount', 'umount', 'wdctl', 'mountpoint', 'lsblk', 'findmnt', 'fstrim', 'losetup', 'zramctl',
         'swapon', 'swapoff', 'blkid', 'findfs', 'wipefs', 'mkswap', 'swaplabel', 'fsck', 'fdisk',
         'sfdisk', 'cfdisk', 'column', 'lslogins', 'lsmem', 'lsipc', 'eject', 'prlimit', 'lsns', 'lscpu',
         'unshare', 'lslocks', 'uuidparse', 'fincore', 'rfkill', 'partx',
         env.installdir + '/sbin'],
